name: NgPixiJS action for Node.js
description: Setup Node.js

inputs:
  node-version:
    description: Node.js version
    required: false
    default: 24.x

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Cache NPM dependencies
      uses: actions/cache@v4
      id: cache-npm-dependencies
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    - name: Install npm 11.10.1
      shell: bash
      run: npm install -g npm@11.10.1

    - name: Install Dependencies
      if: steps.cache-npm-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
