name: 📦 Release

on:
  push:
    branches:
      - release
      - beta
      - '*.x'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      head: ${GITHUB_REF##*/}
  test:
    uses: ./.github/workflows/test.yml
    with:
      head: ${GITHUB_REF##*/}

  release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: git fetch origin ${{ inputs.base }}

      - name: Setup Node.js
        uses: ./.github/actions/nodejs

      - name: Build Libraries
        run: npx nx run-many --projects=tag:type:lib --target=build --configuration=ci --parallel

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
